#!/usr/bin/env bash
nn=$(basename ${PWD})
PROJECT_HOME="${PWD}"
DOCKER_COMPOSE_FILE="${PROJECT_HOME}/docker/docker-compose.yml"
source "${PROJECT_HOME}/docker/utils"

argparse "$@"

case "$ACTION" in
    "start" )
        docker compose \
        -f ${DOCKER_COMPOSE_FILE} up \
        --remove-orphans --build -d;

    ;;
    "stop" )
        if [ ! -z "${APP}" ]; then
            stop_container chatnest
            [ "$?" != 0 ] && exit $?
        else
            docker compose \
            -f ${DOCKER_COMPOSE_FILE} \
            down;
        fi
        ;;
    "logs" )
        docker logs --follow chatnest
        ;;
esac


